#!/bin/sh

# mainブランチではcommitできません。
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  echo "❌ mainブランチではcommitできません。別のブランチを使用してください。"
  exit 1
fi

echo "✔ チェック完了"
exit 0
