#!/bin/sh

# mainブランチではpushできません。
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
  echo "❌ mainブランチではpushできません。pull request を作成してください。"
  exit 1
fi

echo "✔ チェック完了"
exit 0
